#
###################################
# Site wide configuration
####################################
#
title: Rhea Ayase
email: contact@rhea.dev
description: Personal website and blog of Rhea Gustavsson. Passionate VR Dancer, Biker and a Senior Game Developer. Formerly known for her exploits in the Linux world as the .NET QE Lead at Red Hat."
url: https://rhea.dev


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Prague
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Rhea Gustavsson"
  nickname: "Rhea Ayase"
  avatar: avatar.jpg
  job: "writes and teaches C# code on Linux." #".NET Software Engineer<br />Linux Programmer Specialist<br />Azure OnDemand Support"
  bio: "Rhea the domme, wielder of whips, owner of Kass. Passionate VR Dancer, Biker and a Senior Game Developer. Formerly known for her exploits in the Linux world as the .NET QE Lead at Red Hat."
  email: rhea@ayase.eu
  about-url: "https://rhea.dev/about"
  #about-url: "https://rhea.dev/articles/1990-08/Who-is-Rhea"
  disqus-shortname: rheaayase
  discord: https://discord.gg/m2PFpymQb9
  twitter: RheaAyase
  facebook: #username
  google:
    plus: #username
    analytics: UA-87346202-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: RheaAyase
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: radka-janek
  skype: #username
  xing: #username
  instagram: rhea.ayase
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #rhea-ayase
  dribbble: #username
  youtube: RheaAyase
  twitch: #RheaAyase
  soundcloud: rhea-ayase
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  telegram: RheaAyase
  fedora: Rhea
  reddit: #RheaAyase

