#
###################################
# Site wide configuration
####################################
#
title: Rhea Ayase
email: rhea@ayase.eu
description: Personal website and blog of Radka Janek, former game programmer, Community Manager and an active contributor to open source communities. Currently wearing her Red Hat, inspiring the desolate whitespace of Linux world with the delicate C# letters of simplified artificial intelligence.
url: http://rhea-ayase.eu


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Prague
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Radka Janeková"
  nickname: "Rhea Ayase"
  avatar: avatar.jpg
  job: "writes and teaches C# code on Linux." #".NET Software Engineer<br />Linux Programmer Specialist<br />Azure OnDemand Support"
  bio: "Former&nbsp;game&nbsp;programmer with passionate&nbsp;opinions&nbsp;about&nbsp;the&nbsp;industry, Community&nbsp;Manager&nbsp;and&nbsp;active&nbsp;contributor to&nbsp;gaming&nbsp;and&nbsp;open&nbsp;source&nbsp;communities. Currently&nbsp;wearing&nbsp;her&nbsp;RedHat, playing&nbsp;with&nbsp;the&nbsp;delicate&nbsp;C#&nbsp;letters&nbsp;in&nbsp;Linux."
  email: rhea@ayase.eu
  about-url: "http://rhea-ayase.eu/about"
  #about-url: "http://rhea-ayase.eu/articles/1990-08/Who-is-Rhea"
  disqus-shortname: rheaayase
  discord: http://discord.rhea-ayase.eu
  twitter: RheaAyase
  facebook: #username
  google:
    plus: #username
    analytics: UA-87346202-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: RheaAyase
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: radka-janek
  skype: #username
  xing: #username
  instagram: rhea.ayase
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #rhea-ayase
  dribbble: #username
  youtube: RheaAyase
  twitch: RheaAyase
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  telegram: RheaAyase
  fedora: Rhea
  reddit: #RheaAyase

